server:
  port: 8080

spring:
  application:
    name: Disk API
  jmx:
    enabled: true
  main:
    banner-mode: 'off'

  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test;INIT=RUNSCRIPT FROM 'classpath:import.sql';DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: default,dev

---
spring:
  profiles: sit

---
spring:
  profiles: prd

---
spring:
  profiles: test